image: gobraverifier/gobra-ide-base:v2

stages:
  - build
  - test

variables:
  SBT_OPTS: "-Dsbt.global.base=server/sbt-cache/.sbtboot -Dsbt.boot.directory=server/sbt-cache/.boot -Dsbt.ivy.home=server/sbt-cache/.ivy"

build-server:
  stage: build
  before_script:
    - cd server
    # save current directory such that one can return to it after setting symbolic links:
    - cwd=$(pwd)
    # clone Viper dependencies:
    - git clone https://github.com/viperproject/silver.git ../silver
    - git clone https://github.com/viperproject/silicon.git ../silicon
    - git clone https://github.com/viperproject/carbon.git ../carbon
    - git clone https://github.com/viperproject/viperserver.git ../viperserver
    - git clone https://github.com/viperproject/gobra ../gobra
    # print some version numbers:
    - java --version
    - z3 -version
    - node --version
    - npm --version
    - echo "Silver commit:" $(git -C ../silver rev-parse HEAD)
    - echo "Silicon commit:" $(git -C ../silicon rev-parse HEAD)
    - echo "Carbon commit:" $(git -C ../carbon rev-parse HEAD)
    - echo "ViperServer commit:" $(git -C ../viperserver rev-parse HEAD)
    - echo "Gobra commit:" $(git -C ../gobra rev-parse HEAD)
    # create symlinks between and to Viper dependencies:
    - cd ../silicon; ln --symbolic ../silver; cd $cwd
    - cd ../carbon; ln --symbolic ../silver; cd $cwd
    - cd ../viperserver; ln --symbolic ../silver; ln --symbolic ../silicon; ln --symbolic ../carbon; cd $cwd
    - cd ../gobra; ln --symbolic ../silver; ln --symbolic ../silicon; ln --symbolic ../carbon; ln --symbolic ../viperserver; cd $cwd
    - ln --symbolic ../gobra
  script:
    # assemble Gobra server without running unit tests:
    - sbt "set test in assembly := {}" clean assembly
  artifacts:
    paths:
      - server/target/scala-2.12/server.jar
  cache:
    paths:
      - server/sbt-cache/.ivy/cache
      - server/sbt-cache/.boot
      - server/sbt-cache/.sbtboot
      - server/sbt-cache/target

test-server:
  stage: test
  script:
    - sbt test

test-client:
  stage: test
  before_script:
    - cd client
    - npm ci --cache .npm --prefer-offline
  script:
    # start xvfb:
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo ">>> Started xvfb"
    - DISPLAY=":99.0" npm test
  cache:
    paths:
      - client/.npm/
